# Generated by Django 5.1.1 on 2024-09-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.TextField(null=True, verbose_name="Product Image"),
        ),
    ]
