# Generated by Django 5.1.1 on 2024-09-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="Category Name"
            ),
        ),
    ]
